// <auto-generated />
using System;
using AzureDemo.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AzureDemo.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20200404161251_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AzureDemo.Entities.Blog", b =>
                {
                    b.Property<Guid>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Url = "https://example.com"
                        },
                        new
                        {
                            BlogId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Url = "https://example.com"
                        },
                        new
                        {
                            BlogId = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            Url = "https://example.com"
                        },
                        new
                        {
                            BlogId = new Guid("102b566b-ba1f-404c-b2df-e2cde39ade09"),
                            Url = "https://example.com"
                        });
                });

            modelBuilder.Entity("AzureDemo.Entities.Post", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = new Guid("5b1c2b4d-48c7-402a-80c3-cc796ad49c6b"),
                            BlogId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Content = "Commandeering a ship in rough waters isn't easy.  Commandeering it without getting caught is even harder.  In this course you'll learn how to sail away and avoid those pesky musketeers.",
                            Title = "Commandeering a Ship Without Getting Caught"
                        },
                        new
                        {
                            PostId = new Guid("d8663e5e-7494-4f81-8739-6e0de1bea7ee"),
                            BlogId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Content = "In this course, the author provides tips to avoid, or, if needed, overthrow pirate mutiny.",
                            Title = "Overthrowing Mutiny"
                        },
                        new
                        {
                            PostId = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            BlogId = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            Content = "Every good pirate loves rum, but it also has a tendency to get you into trouble.  In this course you'll learn how to avoid that.  This new exclusive edition includes an additional chapter on how to run fast without falling while drunk.",
                            Title = "Avoiding Brawls While Drinking as Much Rum as You Desire"
                        },
                        new
                        {
                            PostId = new Guid("40ff5488-fdab-45b5-bc3a-14302d59869a"),
                            BlogId = new Guid("102b566b-ba1f-404c-b2df-e2cde39ade09"),
                            Content = "In this course you'll learn how to sing all-time favorite pirate songs without sounding like you actually know the words or how to hold a note.",
                            Title = "Singalong Pirate Hits"
                        });
                });

            modelBuilder.Entity("AzureDemo.Entities.Post", b =>
                {
                    b.HasOne("AzureDemo.Entities.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
